version: "3.8"

services:
  r1:
    build: ./
    container_name: r1
    hostname: r1
    networks:
      N_A1:
        ipv4_address: 192.168.1.1
      N_C1:
        ipv4_address: 10.1.0.1
    cap_add:
      - NET_ADMIN

  r2:
    build: ./
    container_name: r2
    hostname: r2
    networks:
      N_C1:
        ipv4_address: 10.1.0.2
      N_C2:
        ipv4_address: 10.2.0.2
      N_A2:
        ipv4_address: 192.168.2.1
    cap_add:
      - NET_ADMIN

  r3:
    build: ./
    container_name: r3
    hostname: r3
    networks:
      N_C3:
        ipv4_address: 10.3.0.3
      N_A3:
        ipv4_address: 192.168.3.1
    cap_add:
      - NET_ADMIN

  r4:
    build: ./
    container_name: r4
    hostname: r4
    networks:
      N_C1:
        ipv4_address: 10.1.0.4
      N_C2:
        ipv4_address: 10.2.0.4
    cap_add:
      - NET_ADMIN

  r5:
    build: ./
    container_name: r5
    hostname: r5
    networks:
      N_C2:
        ipv4_address: 10.2.0.5
      N_C3:
        ipv4_address: 10.3.0.5
    cap_add:
      - NET_ADMIN

  ta1:
    build:
      context: ./
      dockerfile: Dockerfile.terminal
    container_name: t1
    hostname: t1
    command: sh -c "ip route add default via 192.168.1.1; tail -f /dev/null"
    networks:
      N_A1:
        ipv4_address: 192.168.1.10

  ta2:
    build:
      context: ./
      dockerfile: Dockerfile.terminal
    container_name: t2
    hostname: t2
    command: sh -c "ip route add default via 192.168.2.1; tail -f /dev/null"
    networks:
      N_A2:
        ipv4_address: 192.168.2.10

  ta3:
    build:
      context: ./
      dockerfile: Dockerfile.terminal
    container_name: t3
    hostname: t3
    command: sh -c "ip route add default via 192.168.3.1; tail -f /dev/null"
    networks:
      N_A3:
        ipv4_address: 192.168.3.10

networks:
  N_C1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24
          gateway: 10.1.0.254

  N_C2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/24
          gateway: 10.2.0.254

  N_C3:
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.0.0/24
          gateway: 10.3.0.254

  N_A1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.254

  N_A2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.254

  N_A3:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.3.0/24
          gateway: 192.168.3.254
