version: "3.8"

services:
  r1:
    build: ./
    container_name: r1
    hostname: r1
    command: tail -f /dev/null
    networks:
      N_C1:
        ipv4_address: 10.1.0.1
    cap_add:
      - NET_ADMIN

  r2:
    build: ./
    container_name: r2
    hostname: r2
    command: tail -f /dev/null
    networks:
      N_C1:
        ipv4_address: 10.1.0.2
      N_C2:
        ipv4_address: 10.2.0.2
    cap_add:
      - NET_ADMIN

  r3:
    build: ./
    container_name: r3
    hostname: r3
    command: tail -f /dev/null
    networks:
      N_C3:
        ipv4_address: 10.3.0.3
    cap_add:
      - NET_ADMIN

  r4:
    build: ./
    container_name: r4
    hostname: r4
    command: tail -f /dev/null
    networks:
      N_C1:
        ipv4_address: 10.1.0.4
      N_C2:
        ipv4_address: 10.2.0.4
    cap_add:
      - NET_ADMIN

  r5:
    build: ./
    container_name: r5
    hostname: r5
    command: tail -f /dev/null
    networks:
      N_C2:
        ipv4_address: 10.2.0.5
      N_C3:
        ipv4_address: 10.3.0.5
    cap_add:
      - NET_ADMIN

networks:
  N_C1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24
          gateway: 10.1.0.254

  N_C2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/24
          gateway: 10.2.0.254

  N_C3:
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.0.0/24
          gateway: 10.3.0.254
